// js/components/UserPosts.js
const USER_POSTS = [
    {
        id: 1,
        user: 'Mika',
        name: 'OVERSIZE WOOL SHELL',
        tag: '#MORNINGCOMMUTE',
        genre: 'Preppy / 王道',
        mode: 'preppy',
        warmth: 4,
        img: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=700&q=80',
        currentRank: 1,
        prevRank: 3,
        likes: 5200,
        hashtags: ['MorningCommute', 'WoolShell', 'Layering'],
        description: '風が冷たい朝に安心なオーバーサイズシェル。',
        hot: false,
    },
    {
        id: 2,
        user: 'Kou',
        name: 'NEO UTILITY PARKA',
        tag: '#NIGHTRUN',
        genre: 'Minimalist / 個性派',
        mode: 'minimalist',
        warmth: 5,
        img: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=700&q=80',
        currentRank: 2,
        prevRank: 8,
        likes: 7600,
        hashtags: ['Cyberpunk', 'Techwear', 'StreetStyle'],
        description: '防風性能と動きやすさを両立するパーカ。',
        hot: true,
    },
    {
        id: 3,
        user: 'Yui',
        name: 'LANE LINEN SET',
        tag: '#WORKCAMPUS',
        genre: 'Minimalist / 個性派',
        mode: 'minimalist',
        warmth: 3,
        img: 'https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?auto=format&fit=crop&w=700&q=80',
        currentRank: 3,
        prevRank: 4,
        likes: 2800,
        hashtags: ['SlowFashion', 'Minimal', 'Linen'],
        description: 'ナチュラルリネンで作る柔らかい通勤スタイル。',
        hot: false,
    },
    {
        id: 4,
        user: 'Sota',
        name: 'SLIM WOOL SUIT',
        tag: '#CITYLOOK',
        genre: 'Preppy / 王道',
        mode: 'preppy',
        warmth: 4,
        img: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=700&q=80',
        currentRank: 4,
        prevRank: 10,
        likes: 6200,
        hashtags: ['Classic', 'Knitwear', 'IvyStyle'],
        description: '洗練されたウールのスリムシルエット。',
        hot: true,
    },
];
